language: android
dist: trusty
android:
  components:
    # Things needed to have
    - tools
    - platform-tools
    - add-on
    - extra

    # The BuildTools version used by the project
    - build-tools-29.0.1

    # The SDK version used to compile this project
    - android-21

    # Additional components
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during the tests
    - sys-img-armeabi-v7a-android-21
