language: android
jdk: oraclejdk12

env:
  global:
    - ANDROID_API_LEVEL=21
    - ANDROID_EMULATOR_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=29.0.1
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_ABU=armeabi-v7a
    
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDEOID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
  
  licenses:
    - android-sdk-preview-license-.+
    - androis-sdk-license_.+
    
